import pytest
import lxml.etree as ET
import logging # Import it here to access levels
from app.indexer.tei_cleaner import TEICleaner

# Get the logger for this specific module
logger = logging.getLogger("FMB-Pipeline.Tests")

def test_contextual_place_note_linkage(caplog):
    # Set the capture level to INFO so we can see it in the test report
    caplog.set_level(logging.INFO)

    # 1. Setup
    xml_data = """
    <p xmlns="http://www.tei-c.org/ns/1.0">
        Ihre Überkunft nach <placeName xml:id="p1">Berlin<settlement key="STM01">Berlin</settlement></placeName>
        <note type="single_place_comment">Mendelssohn übersiedelte erst 1841.</note>
        gefälligst zu beschleunigen.
    </p>
    """
    namespaces = {'tei': 'http://www.tei-c.org/ns/1.0'}
    root = ET.fromstring(xml_data)
    
    logger.info("Starting test for Place/Note linkage...")

    # 2. Execution
    TEICleaner._context_stack = []
    results = []

    for node in root.xpath("./node()", namespaces=namespaces):
        if isinstance(node, ET._Element):
            # The TEICleaner internal loggers will trigger here
            results.append(TEICleaner.process_node(node, namespaces))
        else:
            results.append(str(node))

    full_text = "".join(results)
    cleaned_text = TEICleaner.clean_whitespace(full_text)
    
    # 3. Validation
    assert "Berlin [STM01]" in cleaned_text
    
    # Check if a specific log message was generated by the TEICleaner
    # This proves the 'logger.info' inside your production code is working!
    assert any("Processing note" in record.message for record in caplog.records)
    
    logger.info(f"Test result: {cleaned_text[:50]}...")
